### ISSUE TITLE
Anchor line dropped when --keep-sequence-order flag

### ISSUE THREAD

**Issue by SchwarzMarek** [s-will/LocARNA#21] opened 2017-05-11 11:54 UTC
Hi,
I've noticed, that mlocarna drops the #A1 anchor sequence (which is present in result.aln when anchors are given) when --keep-sequence-order flag is given. The #A2 line is retained but moved from bottom of the alignment to the top.

The stockholm output file seems unaffected, but it is not sorted.

Moreover, when --keep-sequence-order flag is given, the result_prog.aln contains all sequences and annotations, but it is not sorted, and the result.aln is sorted but in my case, one sequence is missing.

Please see attached files:
[mlocarna.tar.gz](https://github.com/s-will/LocARNA/files/992946/mlocarna.tar.gz)

The issue with A1 anchor is repeatable on the Locarna web interface with snoRNAs predefined dataset. However, I didn't check if the whole sequence disappears as well in the result.aln.

Best regards
Marek Schwarz

**Comment by s-will** [comment] 2017-05-11 12:35
Hi Marek, thanks a lot! This is certainly not the intended behavior ;).

**Comment by s-will** [comment] 2017-05-11 12:54
Hey, the bug should be fixed in the trunk version. (This will be included in the next release.) Thanks, again.

**Closed as completed by s-will** 2017-05-11 12:54 UTC
